/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChatsRouteRouteImport } from './routes/chats/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ProfilesUserIdRouteImport } from './routes/profiles/$userId'
import { Route as ChatsSearchRouteImport } from './routes/chats/search'
import { Route as ChatsChatIdRouteImport } from './routes/chats/$chatId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRouteRoute = ChatsRouteRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRouteRoute,
} as any)
const ProfilesUserIdRoute = ProfilesUserIdRouteImport.update({
  id: '/profiles/$userId',
  path: '/profiles/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsSearchRoute = ChatsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ChatsRouteRoute,
} as any)
const ChatsChatIdRoute = ChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/search': typeof ChatsSearchRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/search': typeof ChatsSearchRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/search': typeof ChatsSearchRoute
  '/profiles/$userId': typeof ProfilesUserIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/about'
    | '/assessment'
    | '/login'
    | '/profile'
    | '/register'
    | '/chats/$chatId'
    | '/chats/search'
    | '/profiles/$userId'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/login'
    | '/profile'
    | '/register'
    | '/chats/$chatId'
    | '/chats/search'
    | '/profiles/$userId'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/about'
    | '/assessment'
    | '/login'
    | '/profile'
    | '/register'
    | '/chats/$chatId'
    | '/chats/search'
    | '/profiles/$userId'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRouteRoute: typeof ChatsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ProfilesUserIdRoute: typeof ProfilesUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRouteRoute
    }
    '/profiles/$userId': {
      id: '/profiles/$userId'
      path: '/profiles/$userId'
      fullPath: '/profiles/$userId'
      preLoaderRoute: typeof ProfilesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/search': {
      id: '/chats/search'
      path: '/search'
      fullPath: '/chats/search'
      preLoaderRoute: typeof ChatsSearchRouteImport
      parentRoute: typeof ChatsRouteRoute
    }
    '/chats/$chatId': {
      id: '/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof ChatsChatIdRouteImport
      parentRoute: typeof ChatsRouteRoute
    }
  }
}

interface ChatsRouteRouteChildren {
  ChatsChatIdRoute: typeof ChatsChatIdRoute
  ChatsSearchRoute: typeof ChatsSearchRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteRouteChildren: ChatsRouteRouteChildren = {
  ChatsChatIdRoute: ChatsChatIdRoute,
  ChatsSearchRoute: ChatsSearchRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteRouteWithChildren = ChatsRouteRoute._addFileChildren(
  ChatsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRouteRoute: ChatsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ProfilesUserIdRoute: ProfilesUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
